### ISSUE TITLE
Fill DB with given Data

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#10]
Ziel ist es die Datenbank mit den gegebenen Daten zu füllen, zusätzlich sollte ein "Dump" erstellt werden und auf github hochgeladen werden, damit die DB lokal übernommen werden kann zum testen.

**Comment by DerBene** [comment]
Hierbei Bitte beachten: Es können manche Einträge nicht erstellt werden ohne abhängigkeit. So kann kein "Medien" erstellt werden, wenn keine Persönlichkeit existiert. Hier für die jeweiligen auftretenden Fälle etwas wie "Unbekannt" hinzufügen

**Comment by DerBene** [comment]
Die Daten müssen noch auf den Server der DHBW gelegt werden

**Comment by peterhusenbeth** [comment]
jo is getan, kp aber wie genau^^
