### ISSUE TITLE
Bilder auf die Website bringen

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#12]
Die Bilder zu den Personen sollen auf der Website angezeigt werden, hierzu ist zu überlegen wie die Bilder abgerufen und gerendert werden

**Comment by DerBene** [comment]
Zusätzlich ist hier die Darstellung in de Reiter "Persönlichkeiten" anzupassen. Hier soltle ein Bild der Person stehen und darunter deren Text

**Comment by DerBene** [comment]
Die Bilder liegen im richtigen Ordner und können einfach in php abgerufen werden, jedoch hat dies zum jetzigen Zeitpunkt keinen Sinn, ohne dass die Darstellungen der Persönlichkeiten fertig ist. Wenn die Darstellung fertig ist, dann können sie eingefügt werden, sofern das nicht schon durch die neue Darstellung geschehen ist.

**Comment by smlhome** [comment]
Also bisher werden ja nur die Dateipfade angezeigt, aber es soll wenn möglich dort das bild und nicht der Pfad angezeigt werden

**Comment by DerBene** [comment]
Bilder wurden statisch eingefügt, zur Präsentation,d as muss jedoch zur Webengineering abgabe noch geändert werden.
