### ISSUE TITLE
Homepage anpassung

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#16]
Es sollte die Ansicht der Homepage angepasst werden. Hierbei ist zunächst eine Sinnvolle Einteilung/Darstellung für die Homepage zu entwerfen. Später sollte diese Implementiert werden, da sie für die Präsentation benötigt wird. 
Evtl ist hier eine Abstimmung mit dem Team erforderlich.

**Comment by smlhome** [comment]
Also auf der Homepage ein paar Ideen:
Große Ankündigung der derzeitigen Ausstellung mit direktem Link.
Zeitstrahl der Epochen mit Link zu den Epochen.
Slideshow mit 3 Personen mit Link.

**Comment by peterhusenbeth** [comment]
wurde schonmal bissl gepimpt, aber natürlich noch net fertig. Was aber glaub auch nicht das Ziel dieser Issue war.
