### ISSUE TITLE
in Bereich : Kategorien, Epochen, Geographisch, Medien

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#18]
Die Tabellen die aus der Datenbank erstellt werden, sollen grafisch Angepasst und aufgewertet werden.
Hierbei ist "www.museum-digital.de" als Vorlage verwendbar.
Ziel ist kein 1:1 Nachbau, sonder nur eine Verbesserte Darstellung der Daten aus der Tabelle.

**Comment by smlhome** [comment]
Also am besten die Tabellenzeile einfach nach der y-Achse ausrichten und am besten bei Persönlichkeiten und Austellung: ein Bild, darunter namen und Zitat oder so, darunter link zu der dazugehörigen epoche und kategorie. Danke

**Comment by DerBene** [comment]
Die neue Form muss noch für Webengineering an allen angepasst werden

**Comment by DerBene** [comment]
Zusätzlich muss bei den m-n beziehungen (bsp: "Persoenlichkeiten Has Epochen"), nachdem die DArstellung angepasst wurde noch angepasst werden, dass nicht die ID der jewilig zusammengehörernden Objekte angeziegt wird, sondern die Namen
