### ISSUE TITLE
Erstellung des relationales Schemas

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#22]
Es muss das relationale Schema erstellt werden (Die Tabellen, zusammen mit den "mix-Tabellen" welche die m-n beziehungen in form der Keys beinhalten.

**Comment by smlhome** [comment]
Das Schema habe ich lokal gespeichert, kann ich auch hochladen

**Comment by smlhome** [comment]
Muss man leider noch kurz bearbeiten und die ö's und so ändern ... oder vielleicht kann man auch die aktuelle nochmal exportieren als Schema?

**Comment by DerBene** [comment]
Ist erstellt udn hochgeladen

**Comment by DerBene** [comment]
Ist erstellt und hochgeladen
