### ISSUE TITLE
Create-Statements (in fertiger Version)

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#23]
Die Create Statements sind abzugeben und dabei alle von der Datenbank selbst erstellen informationen zu entfernen

**Comment by smlhome** [comment]
Ich kann die fertige Datenbank dann exportieren und die Statements friesieren so wie sie es gerne hätte.

**Comment by DerBene** [comment]
Ok, dann weise ich dir das Tciket zu, danke!

**Comment by DerBene** [comment]
Sind fertig und wurden hochgeladen
