### ISSUE TITLE
Dokumantation der Ergebnisse

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#25]
Es sollten alle Komponenten in einer Einheitlichen Dokumentation erklärt werden. Zusätzlich sollte der Code möglichst gut Kommentiert sein.

**Comment by smlhome** [comment]
Ich muss noch ein paar Kommentare in meinen Code packen, bitte macht ihr das direkt wenn ihr es schreibt. Spart viel Arbeit! danke

**Comment by DerBene** [comment]
Dokumentation muss noch erstellt werden

**Comment by DerBene** [comment]
erstellt, revied, hochgeladen
