### ISSUE TITLE
Abgabe der Aufgabe in Moodle

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#26]
Folgende Dinge müssen bis 19.04.2017 hochgeladen sein:
-Präsentation als Datei (evtl pdf)
-ER-Modell
-Relationaler Entwurf (mit SQL skript mit create statements)
-Programmcode in gepacktem format (.zip)
-Alles sonstige zugehörige

**Comment by smlhome** [comment]
Wer macht die Präsentation? Ich kann das ER-Modell liefern und den Relationalen Entwurf.

**Comment by DerBene** [comment]
Ich werde die Präsentation erstellen.

Es muss irgendwo im Programmcode jedoch noch ein "Select" Statement als Beispiel exisiteren, das sollte evtl irgendwo noch eingefügt werden vor der Abgabe.

**Comment by smlhome** [comment]
https://elearning.dhbw-stuttgart.de/moodle/mod/forum/discuss.php?d=3000

**Comment by smlhome** [comment]
Hier der Link zu den ergebnissen von Markus, kann man mal reinschauen was der alles abgegeben hat

**Comment by DerBene** [comment]
ist abgegeben
