### ISSUE TITLE
Ausstellungsseite

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#28]
Hierbei sollte ein "Register" auf der Seite erstellt werden, welche nur momentan ausgestellte Exponate darstellt. Hierzu muss erst geprüft werden, ob ein entsprechender DB Eintrag dafür vorhanden ist. Wenn nicht, muss dieser erst erstellt werden und danach richtig ausgewertet werden. (Einfache Abfrage, ob ture oder false, je nachdem eben darstellen oder nicht).
Es ist hierbei die Darstellung der anderen "Register" zu übernehmen um eine Einheitlichkeit der Seite zu wahren.

**Comment by smlhome** [comment]
Ich adde noch einen Reiter in die Hauptleiste mit Austellung. Dort soll dann Alles zu einer Person auf einem Haufen sein, also Person, Kategorie, Medien und Epoche am besten unter einem Bild von der Person zusammengestellt. Danke

**Comment by smlhome** [comment]
Also man muss nur noch das Template für die Darstellung von Marcel für die Ausstellung auch übernehmen.

**Comment by DerBene** [comment]
Wird für die Datenbank Präsentation so gelassen muss für Webengineering noch angepasst werden
