### ISSUE TITLE
Erstellung Präsentation und Abgabe der Präsentation

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#32]

**Comment by DerBene** [comment]
Es darf sich ruhig bei der Datenbankenpräsentation orientiert werden, jedoch ist auf die Anforderungen von WEbengineering zu achten, da dort DB-Modelle nicht Interessieren und z.b. die Aufgabenverteilung zusammen mit dem jeweiligen Aufwand (in Stunden) mit reingenommen werden muss. (ANFORDERUNGEN LESEN!!!!!!!)

Bei fragen bitte an mich wenden, Ansonsten wird die Präsentation am Montag angeschaut und beprochen ob das so passt.

**Comment by peterhusenbeth** [comment]
Präsentation erstellt. Muss noch ergänzt und aufgearbeitet werden. Soweit alle Anforderungen eingebaut, Inhalt fehlt bei manchen allerdings noch
