### ISSUE TITLE
Es sollen im source code sowohl SELECT,INSERT,UPDATE und DELETE verwendet werden

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#33]
zur abgabe sollen diese Befehle jeweils 2mal irgendwie verwendet werden. Sie dienen nur zur Abgabe, damit gezeigt wird dass wir sie benutzen können.

**Comment by smlhome** [comment]
müssen wir des in den programmcode selber reinbauen? oder reicht des in den sql statements?
