### ISSUE TITLE
Responisve machen der Website

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#35]
Die Website soll voll responsive sein, d.h. auch auf Mobilgeräten funktionieren. Momentan Probleme bei Tebellen mit Text und bei Überschriften der Tabellen

**Comment by peterhusenbeth** [comment]
Scrolling auf der homepage mit mobilen Geräten ist noch sehr träge. Bilder oder JS optimieren, dann sollte das auch auf der homepage besser werden.

**Comment by DerBene** [comment]
Leiste Oben, vorallem "Hompage" button fixen auf kleinen bildschirmen/Handys

Evtl noch Zeitstrahl an eine Seite, damit text nicht aus Boxen rausläuft
