### ISSUE TITLE
Runterskalieren der Bilder

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#38]
Die Website "gtmetrix.com" zeigt an wie können Performance erhöhungen erhalten durch das Runterskalieren der Bilder. Hierzu gibt es eine Website die dies macht (wurde in der Vorlesung besprochen), die b-ilder müssten hier komprimiert werden und neu eingefügt werden. Um die Website zu bekommen können gern Mitstudenten gefragt werden.

**Comment by peterhusenbeth** [comment]
Hab die Bilder mit tinypng.com komprimiert, kann sie aber nur aus dem DHBW-Netzwerk hochladen.

**Comment by peterhusenbeth** [comment]
Optimierte Versionen der Bilder sind auf dem Server.

**Comment by DerBene** [comment]
getestet, ob gtmetrix noch was anzeigt? wenn es da nichts mehr anzeig, hinsichtlich der Bilder, kann das Issue geschlossen werden

**Comment by DerBene** [comment]
Getestet, Grade A, damit feritg
