### ISSUE TITLE
Checken der Seite mit gtmetrix und ssllabs vor abgabe

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#39]
vor der Abgabe sollte die Seite dort nochmal auf Geschwindigkeit und Sicherheit überprüft werden

**Comment by peterhusenbeth** [comment]
Ich wollte den Punkt "YSLOW/AddExpiresHeaders: Grade F" verbessern. Habe dazu die .htaccess angepasst, es gab aber keine Besserung...
