### ISSUE TITLE
Link bei Slideshow fixen

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#41]

**Comment by Stammez92** [comment]
Hab eine neue Slideshow von bootstrap eingebaut, die auch für Handys optimiert ist. Das mit dem Link hab ich auch gefixt. Falls ihr das meint, dass wenn man aufs bild klickt das man dann zu "missing Controller" Seite weitergelietet wird.

**Comment by DerBene** [comment]
Es sit garnichtmehr möglich draufzuklicken also ok
