### ISSUE TITLE
RestApi

### ISSUE THREAD

**Issue by DerBene** [DerBene/VirtuellesMuseum-Grp3#5]
Informationen zu RestApi sammeln und deren Aufgabe verstehen.

**Comment by smlhome** [comment]
https://book.cakephp.org/3.0/en/development/rest.html

**Comment by DerBene** [comment]
Es ist bis zur abgabe noch eine funktioneirende Rest-API zu implementieren

**Comment by smlhome** [comment]
Ich hätte gesagt wir benutzen des schon, denn Laut dem Eintrag sind die Statements Rest, die wir schon implementiert haben?

**Comment by DerBene** [comment]
Die Rest API muss zusätzlich noch einen Zugriffsschutz haben

**Comment by DerBene** [comment]
http://miftyisbored.com/complete-restful-service-client-cakephp-tutorial/
http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/

**Comment by smlhome** [comment]
Benutzen durch die Urls wie:
http://localhost/VirtuellesMuseum-Grp3/kategorien.json?sort=Name
http://localhost/VirtuellesMuseum-Grp3/kategorien.json?limit=2
oder siehe:
http://www.bravo-kernel.com/2015/04/how-to-use-a-cakephp-3-rest-api/

**Comment by smlhome** [comment]
funktioniert nach ausführen dieser Zeilen in der Commandozeile:

composer require friendsofcake/crud:~4.0
bin/cake plugin load Crud
